### ISSUE TITLE
Support for `jakarta.*` namespace in `jaxrs-*` generators

### ISSUE THREAD

**Issue by erdlet** [swagger-api/swagger-codegen-generators#1054]
I tried to generate an API for a Jakarta EE 9 project but recognized that there's no `jaxrs-*` generator supporting the `jakarta.*` namespace. Because the `jakarta.*` namespace is the future of all Jakarta EE specifications, it makes sense to support the namespace at least inside the `jaxrs-*` generators.

Is there something on your roadmap regarding this issue or is this a completely new request? In case it's the latter, I'd offer my help to implement the support for this.

**Comment by mkjensen** [comment]
Related: https://github.com/swagger-api/swagger-codegen/issues/11797

**Comment by s-jepsen** [comment]
I'm thinking of taking a stab at this for spring-boot-3.

Since spring-boot 3 is basically a switch to Jakarta and a minimum of java17 - i'm thinking of doing a new dedicated spring-boot-3 library target.

Is this the way to go?

**Comment by s-jepsen** [comment]
@HugoMario: Looking at the spring-boot and spring-cloud libraries - they support spring 1.5 (which was released Feb 2017)?
- Is this something I can remove to make the libraries more simple?

**Comment by mkjensen** [comment]
Even commercial support has ended for Spring Boot 1.5, so it makes sense to stop supporting that?

See https://spring.io/projects/spring-boot#support for more details.

**Comment by s-jepsen** [comment]
So I'm basically suggesting the below 3 or 4 tasks.

- [ ] Remove Spring Boot 1.x support 
- [ ] Upgrade Spring Boot 2.1.16 to latest Spring Boot 2.7.x
- [ ] Introduce Spring Boot 3.x support.
- [ ] Extra: Possibly remove some of the variants of dateLibrary support (threetenbp, java8-localdatetime, joda, legacy) - although this will also affect other Java based generators???

**Comment by mlemnian** [comment]
All the java related generators need to be updated:
* especially JEE-related generators (if it's not already done)

**Comment by HugoMario** [comment]
addressed by #1091
