### ISSUE TITLE
Spring Server Side Code Generator Not working for openapi 3.0.0

### ISSUE THREAD

**Issue by FossilBlade** [swagger-api/swagger-codegen-generators#106]
Hi,

Server side code generator for openapi: 3.0.0 in not generating code for spring. There is no file which is being downloaded nor any error being thrown.

**Comment by HugoMario** [comment]
hello @FossilBlade can you please share what command did you use?

**Comment by realjax** [comment]
Maybe this is what he meant, It is also not working here https://editor.swagger.io/ 

Try generating some 3.0.0. server side code usiong spring.

**Comment by yochannah** [comment]
I've experienced the same issue. [this file](https://github.com/yochannah/wizard-api-specs/commit/9d2908f3cc1cdf47c2ca760ccb31af0b715720c1) pasted into the swagger editor results in the following 500 error response in my console:

```json
{"code":500,"message":"There was an error processing your request. It has been logged (ID: 2be0c5b5e299b7ce)"}
```

![image](https://user-images.githubusercontent.com/9271438/43594093-44fe25a0-9671-11e8-9424-67def4e48c0b.png)

**Comment by bmistry13** [comment]
I am experiencing the same issue as reported by @yochannah.  Please let us know the resolution.

**Comment by HugoMario** [comment]
can you guys please try with [codegen CLI](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/swagger-codegen-cli-3.0.0-20180717.153005-90.jar) it will take a couple of weeks to have a new release for editor.

**Comment by bmistry13** [comment]
@HugoMario ,  codegen CLI worked for me.  Thanks for help !

**Comment by gowthamantoni** [comment]
Hi @HugoMario  &  @bmistry13 , I have tried with codeGen CLI JAR.. I am getting the Swagger 2.0 server code for spring boot..
This is the command I tried:
java -jar swagger-codegen-cli-3.0.0-20180717.153005-90.jar generate -i ./openapi3.0.json -l spring -o Generated

What am I missing?

**Comment by HugoMario** [comment]
this is fixed in recent versions
