### ISSUE TITLE
Merge PR and release new version?

### ISSUE THREAD

**Issue by radarsh** [swagger-api/swagger-codegen-generators#1101]
Hi

Apologies for raising a non-issue but I'm really keen to get https://github.com/swagger-api/swagger-codegen-generators/pull/1099 merged and a new version released. Looking at the project activity it doesn't look like recent issues are being dealt with. So I really had no other way to communicate with the project members.

This fix is quite important for us as it addresses a number of issues with OpenAPI codegen for the JavaSpring language. I would appreciate it greatly if one of the core members of the project could take a look and help merge it and release a new version.

Thanks

**Comment by Fyro-Ing** [comment]
+1 on my 2 PR 

i supposed @frantuma & @HugoMario are volunteer (i'm not sure fort the english word)

**Comment by HugoMario** [comment]
#1099 is already merged, it will be available for next release.
