### ISSUE TITLE
Generator typescript-axios doesn't use Basic auth

### ISSUE THREAD

**Issue by Babbiorsetto** [swagger-api/swagger-codegen-generators#1121]
I encountered this issue while using the [online swagger editor](https://editor.swagger.io/)'s generate client feature, which I believe is using swagger-codegen under the hood.
The resulting client's api files contain the line
```// authentication basicAuth required```
but no authentication headers are set.

I traced this line back to the template file
https://github.com/swagger-api/swagger-codegen-generators/blob/47d688651245379ab3e68e2f20466af2ad00a580/src/main/resources/handlebars/typescript-axios/apiInner.mustache#L57
I don't know this template syntax too well, but I believe the issue lies in the `{{#isBasicBasic}}` condition where other templates use `{{#isBasic}}` for the same check. I believe this may be a typo that is causing the template to skip this section entirely.

#### Axios:
https://github.com/swagger-api/swagger-codegen-generators/blob/47d688651245379ab3e68e2f20466af2ad00a580/src/main/resources/handlebars/typescript-axios/apiInner.mustache#L76-L81
#### Fetch:
https://github.com/swagger-api/swagger-codegen-generators/blob/1e8676940cbbeeaf14134f4958dc5b846f3d370d/src/main/resources/handlebars/typescript-fetch/api.mustache#L132-L137

On the same note, the problem may also be present for Bearer token authentication since the check uses `{{#isBasicBearer}}` which isn't used in any other template.

**Comment by HugoMario** [comment]
fixed by https://github.com/swagger-api/swagger-codegen-generators/issues/1121
