### ISSUE TITLE
Fixing jakarta mistake

### ISSUE THREAD

**Issue by Fyro-Ing** [swagger-api/swagger-codegen-generators#1145]
Looks like "import javax.xml.bind.annotation.*;\n" is expected here.
@HugoMario, Please correct me if I`m wrong

_Originally posted by @OleksandrShkurat in https://github.com/swagger-api/swagger-codegen-generators/pull/1091#discussion_r1188947773_

**Comment by HugoMario** [comment]
makes sense @Fyro-Ing thanks for fix

**Comment by HugoMario** [comment]
fixed by #1146
