### ISSUE TITLE
php syntax error 

### ISSUE THREAD

**Issue by ifrolikov** [swagger-api/swagger-codegen-generators#116]
Codegen generate client with syntax error for php language:

in models:
![image](https://user-images.githubusercontent.com/19207727/42433738-468c11a0-8359-11e8-828e-5e8b368d8a30.png)

in Api methods:
![image](https://user-images.githubusercontent.com/19207727/42433755-6131fe48-8359-11e8-909c-d09c785e6019.png)

**Comment by HugoMario** [comment]
hey @ifrolikov , this error was fixed with #118 , can you please check it when you have a chance?

**Comment by ifrolikov** [comment]
Hey @HugoMario , there are still some places:

- https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/resources/v2/php/api.mustache#L101
- https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/resources/v2/php/api.mustache#L127
- https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/resources/v2/php/model_generic.mustache#L59

Thank you!

**Comment by ifrolikov** [comment]
I was create new issue, because this issue was closed

**Comment by HugoMario** [comment]
oh sorry about it, Github closed it automatically because i refenced this in a PR, but yea, let's use the new one. Thanks!
