### ISSUE TITLE
[typescript-angular] '}' missing to close the class in api.service.mustache

### ISSUE THREAD

**Issue by pmacouin** [swagger-api/swagger-codegen-generators#119]
Hello,

At the end of the template, one '}' is missing between {{/operation}} and {{/operations}}.

```
{{/operation}}
}
{{/operations}}
```

**Comment by pmacouin** [comment]
For information, commit [https://github.com/swagger-api/swagger-codegen-generators/commit/d66b81b83883d29e9123bae53f9346f7d7e2b36f#diff-f1ba60859c16c84ea320c25e52d948f9](https://github.com/swagger-api/swagger-codegen-generators/commit/d66b81b83883d29e9123bae53f9346f7d7e2b36f#diff-f1ba60859c16c84ea320c25e52d948f9) has deleted the '}' (line 337)

**Comment by HugoMario** [comment]
This has been fixed in latest releases

**Comment by HugoMario** [comment]
fixed by https://github.com/swagger-api/swagger-codegen-generators/pull/281
