### ISSUE TITLE
Build fails because 3.0.0-SNAPSHOT is not deployed to maven repo

### ISSUE THREAD

**Issue by pavog** [swagger-api/swagger-codegen-generators#12]
The recent builds fail because the new 3.0.0-SNAPSHOT of swagger-api/swagger-codegen (io/swagger/swagger-codegen/3.0.0-SNAPSHOT/) is not getting pushed to the maven repo.
As you can see here: https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen/3.0.0-SNAPSHOT/

To fix this you have to enable the "push to maven" feature again:

- Go to: https://github.com/swagger-api/swagger-codegen/blob/3.0.0/.travis.yml
- Remove the # in the "after_success" section

The swagger-codegen is renamed to "swagger-codegen-project" in 3.0.0. Maybe you have to adjust this in the pom.xml.

**Comment by webron** [comment]
@pavog I see the snapshot there...?

**Comment by pavog** [comment]
But only Jan 10, Jan 11, Jan 12.
Newer snapshots are missing.

**Comment by webron** [comment]
Right you are, will look into it.

**Comment by HugoMario** [comment]
thanks @pavog, this issue has been fixed so let's close it. But please let me know if it still present for you.
