### ISSUE TITLE
[typescript-angular] Packaging with ngPackagr has been lost between 2.0 and 3.0

### ISSUE THREAD

**Issue by pmacouin** [swagger-api/swagger-codegen-generators#120]
Hello,

Please merge the he pull request [https://github.com/swagger-api/swagger-codegen/pull/7984](https://github.com/swagger-api/swagger-codegen/pull/7984).

In templates, there is a use of variables 'useNgPackagr' and 'useOldNgPackagr' but never set in TypeScriptAngularClientCodegen.java.
There is also a 'ng-package.mustache' who is never used.

**Comment by HugoMario** [comment]
hello @pmacouin,

It looks merged.

**Comment by pmacouin** [comment]
Hello @HugoMario,
Yes in swagger-codegen project but not entirely in swagger-codegen-generators project. Templates seems to be, but not Java classes (like TypeScriptAngularClientCodegen.java).

**Comment by HugoMario** [comment]
ah ok, yea we're still migrating/implementing these classes from codegen 2 to 3

**Comment by pmacouin** [comment]
Ok, thanks.

**Comment by HugoMario** [comment]
i'll use this ticket for the mentioned language and let you know.

**Comment by hypery2k** [comment]
any news on this stuff? At least with Angular 9 the current v3 approach doesn't work with Ivy anymore

**Comment by hypery2k** [comment]
any plan for releasing a new version?

**Comment by HugoMario** [comment]
this is already implemented, so going to close it
