### ISSUE TITLE
php syntax error #116

### ISSUE THREAD

**Issue by ifrolikov** [swagger-api/swagger-codegen-generators#121]
Hey! I create new issue, because previous issue was closed.
There are {{#hasMore}} attribute  was still in some places:

- src/main/resources/v2/php/README.mustache
- src/main/resources/v2/php/api.mustache
- src/main/resources/v2/php/api_doc.mustache
- src/main/resources/v2/php/model_generic.mustache

Thank!

**Comment by ifrolikov** [comment]
https://github.com/ifrolikov/swagger-codegen-generators/pull/2/commits/352b1ca2c87654a2350bd9642189fd7d4ea5b283

my fork

**Comment by ifrolikov** [comment]
Ping :)

**Comment by HugoMario** [comment]
Hey @ifrolikov thanks for your ping, i had missed it this one. 

i'm going to check it and create a PR.

**Comment by HugoMario** [comment]
@ifrolikov can you create the PR from your fork so we can merge your changes here?

**Comment by ifrolikov** [comment]
Hey, @HugoMario! I'm sorry, that I write really often, but it is important to me. Swagger codegen get an old snapshot of swagger-codegen-generators while building:
![image](https://user-images.githubusercontent.com/19207727/43118116-095e3c74-8f19-11e8-9f82-23b023d15628.png)
Is this problem of build,  which you told me?

**Comment by HugoMario** [comment]
It's ok @ifrolikov, feel free to ping any time you need. it should look for latest, let me check this and let you know.

**Comment by HugoMario** [comment]
@ifrolikov what command are you using for building, would you try with:
```
mvn clean install -U
```
in case you're using a different one?

**Comment by ifrolikov** [comment]
I'm build image from dockerfile:
![image](https://user-images.githubusercontent.com/19207727/43126160-9eb1299c-8f34-11e8-8f17-1eedfc766600.png).

I'm look repo https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-generators/1.0.0-SNAPSHOT/ and latest version of snapshot is 2018-07-20.  Should not a new version of the snapshot be created after my PR merged? (https://github.com/swagger-api/swagger-codegen-generators/pull/126)

**Comment by HugoMario** [comment]
I think this is related to the circular dependency [issue](https://github.com/swagger-api/swagger-codegen/issues/8016) we have in `swagger-codegen` repo for 3.0.0.

We need to trigger a build on swagger-codegen in order to fix this. This circular dependency issue should be fixed with project refactoring tasks that we're working right now.

I'll try to manually fix this temporary and let you know.

**Comment by pavog** [comment]
Hey I think you can close this issue now, since #123 and #124 have been merged.

**Comment by ifrolikov** [comment]
I forgot about it, thanks!
