### ISSUE TITLE
[ASPNETCORE] bad character in generated file

### ISSUE THREAD

**Issue by Bobdugrand8** [swagger-api/swagger-codegen-generators#1232]
**Description**
When using the generator for ASPNETCORE, it add a bad character that blocks the project to open.

**Swagger-codegen version**
3.0.51 on https://editor.swagger.io/

**Swagger declaration file content or url**
The default PETStore is also bugged

**Command line used for generation**
Steps to reproduce
Generate the aspnetcore server.
Try to open the project in visual studio (or rider)
The project fail to open.

**Related issues/PRs**
Suggest a fix/enhancement
The error is in IO.swagger.csproj:

**Comment by HugoMario** [comment]
fixed by https://github.com/swagger-api/swagger-codegen-generators/pull/1233
