### ISSUE TITLE
[jaxrs-jersey] @PATCH not found.

### ISSUE THREAD

**Issue by HugoMario** [swagger-api/swagger-codegen-generators#142]
i'm not sure yet, but i think this annotation does not longer exist. Need to find out what to do with endpoints that uses this method, keeping in mind that the [definition](https://gist.github.com/HugoMario/5292d9936367ac145ba80e895793e003) used to reproduce this issue is on OAS 2 format.

Related to this, there are runtime errors that need to be fixed, same problem reported at https://github.com/swagger-api/swagger-codegen/issues/8530

**Comment by reta** [comment]
The `@PATCH` become part of JAX-RS 2.1 spec, may we use it instead (and update Jersey dependency if needed)?

**Comment by HugoMario** [comment]
thanks @reta, that fixes the build problem

**Comment by frantuma** [comment]
fixed in #144
