### ISSUE TITLE
generate python-flask server stubs from openapi 3 definition

### ISSUE THREAD

**Issue by mnagel** [swagger-api/swagger-codegen-generators#153]
Hello there,

https://editor.swagger.io/ direct me here for questions about the server code generation.
My question is:
Is it correct that at the moment python-flask server stubs can be generated from swagger 2 definitions but not yet from openapi 3 definitions? If it is correct, are there any plans for the addition of this feature?

Best Regards
Michael

PS: is this the place to report general issues with the hosted instance of the swagger editor? There are some 500 server errors and some mixed content errors when using HTTPS...

**Comment by HugoMario** [comment]
Hello @mnagel, yes' i hope we get this generator soon for openapi 3.

**Comment by chinmayprabhudesai** [comment]
Any updates on this?

**Comment by HugoMario** [comment]
@chinmayprabhudesai just added python client, need to add this one to prio tasks

**Comment by matthaeusheer** [comment]
Any updates on this issue? Cheers

**Comment by chinmayprabhudesai** [comment]
> Any updates on this issue? Cheers

#292 was Merged into the master branch. It There's a python client generator but I don't see a server generator

**Comment by HugoMario** [comment]
sorry for delay guys, just added flask connexion with this PR #387

**Comment by matthaeusheer** [comment]
When will the python-flask server generation for openapi3 be available on SwaggerHub?

**Comment by anselmos** [comment]
@HugoMario It looks like you're missing : 

```java
        if (StringUtils.isBlank(templateDir)) {
            embeddedTemplateDir = templateDir = getTemplateDir();
        }
```
At PythonFlaskConnexionCodegen.java - otherwise it does not read template-dirs properly and just skips to default from jar. Related issue : https://github.com/swagger-api/swagger-codegen/issues/9363

**Comment by HugoMario** [comment]
thanks @anselmos for this catch!

**Comment by HugoMario** [comment]
`python-flask` generator has been added, so i think it's time to close this issue.
