### ISSUE TITLE
TypeScriptAngular: {{#isBodyAllowed}} not available in templates

### ISSUE THREAD

**Issue by loeti** [swagger-api/swagger-codegen-generators#170]
In the 'typescript-angular.mustache' template the {{#isBodyAllowed}} is used to differentiate among other between the HttpClient.get and HttpClient.post method.

Because the {{#isBodyAllowed}} is not there the 'body' parameter is not set in the HttpClient.post method. There is no compilation error because of the optional 'options' parameter, that is send instead the body as message payload. 

I can't find a workaround e.g. editing the templates. I have to go back to codegen version 2.3.0
`{{#useHttpClient}}
        return this.httpClient.{{httpMethod}}{{#isResponseFile}}<{{#returnType}}{{{returnType}}}{{#isResponseTypeFile}}|undefined{{/isResponseTypeFile}}{{/returnType}}{{^returnType}}any{{/returnType}}>{{/isResponseFile}}(`${this.basePath}{{{path}}}`,{{#isBodyAllowed}}
            {{#bodyParam}}{{paramName}}{{/bodyParam}}{{^bodyParam}}{{#hasFormParams}}convertFormParamsToString ? formParams.toString() : formParams{{/hasFormParams}}{{^hasFormParams}}null{{/hasFormParams}}{{/bodyParam}},{{/isBodyAllowed}}
 `

**Comment by mtormento** [comment]
Hi loeti,
the workaround that worked for me (actually I proposed it as a fix for this issue) is to rename #isBodyAllowed to #bodyAllowed.

**Comment by colep-ntap** [comment]
@mtormento - How are you able to rename that given and then generate based on your change given that the templates are now in their own repository. I'm struggling to figure out how to point my instance of swagger-codegen at my instance of swagger-codegen-generators.

**Comment by MBcom** [comment]
`#hasBodyParams` worked for me like in the kotlin generator  
a working codegen for typescript angular can be found here https://github.com/MBcom/swagger-codegen/ (already includes the fixed generator package) (fixes #170, #224) just run `mvn clean package` to get the working cli

**Comment by loeti** [comment]
The property #isBodyAllowed is with the version v1.0.8 available. Works for me.

**Comment by loeti** [comment]
The property #isBodyAllowed is with the version v1.0.8 available. Works for me.
POST operations with empty body generate correct angular typescript service classes now.
