### ISSUE TITLE
[typescript-angular] Missing curly brace in the generated service

### ISSUE THREAD

**Issue by mtormento** [swagger-api/swagger-codegen-generators#224]
### Description
The generated classes for services are invalid, because a curly brace is missing at the end.

I found this issue on swagger-codegen project:
https://github.com/swagger-api/swagger-codegen/issues/8857
but I think it belongs here.

**Comment by MBcom** [comment]
a working codegen for typescript angular can be found here https://github.com/MBcom/swagger-codegen/ (already includes the fixed generator package) (fixes #170, #224) just run mvn clean package to get the working cli
