### ISSUE TITLE
SNAPSHOT not uploaded to https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-generators/?

### ISSUE THREAD

**Issue by The-Alchemist** [swagger-api/swagger-codegen-generators#23]
Looking at https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-generators/1.0.0-SNAPSHOT/, the latest is 1/28/2018.

Is this accurate?

**Comment by webron** [comment]
This _should_ be fixed now. 🤞

**Comment by The-Alchemist** [comment]
Confirmed!
