### ISSUE TITLE
Inheritance is not processed correctly for generated Interfaces 

### ISSUE THREAD

**Issue by Andy2003** [swagger-api/swagger-codegen-generators#237]
For the following API

    openapi: 3.0.0
    info:
      version: '1.0'
      title: Testinheritance
    paths:
      /cat:
        post:
          requestBody:
            content:
              '*/*':
                schema:
                  $ref: '#/components/schemas/Cat'
          responses:
            200:
              description: OK
    components:
      schemas:
        Pet:
          type: object
          discriminator:
            propertyName: dtype
          properties:
            name:
              type: string
        Cat:
          type: object
          allOf:
            - $ref: '#/components/schemas/Pet'

This code is generated:

Spring:

    ResponseEntity<Void> catPost(@ApiParam(value = ""  )  @Valid @RequestBody Object body);

Java:

    public com.squareup.okhttp.Call catPostCall(Object body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException

Typescript-Angular:

    public catPost(body?: any, observe?: 'body', reportProgress?: boolean): Observable<any>;

The body param is of type `Object` instead of `Cat`

**Comment by sohrab-** [comment]
I am seeing this too. Interestingly, it determines the schema just fine if used in the response body.

**Comment by HugoMario** [comment]
fixed with #628
