### ISSUE TITLE
Unable to handle custom content types

### ISSUE THREAD

**Issue by marcoreni** [swagger-api/swagger-codegen-generators#25]
In OpenAPI specification we define the content type before describing the schema.

My response is declared as follows:
```yaml
      responses:
        '200':
          description: OK
          content:
            text/javascript:
              schema: 
                $ref: '#/components/schemas/Response'
```

But after generating my Java client, if I try to consume the API, I receive an exception:
` Content type "text/javascript; charset=utf-8" is not supported for type: class com.example.model.Response `

Checking the source code, this is the block that generates the exception
```java
\\ ApiClient.java#deserialize()

        String contentType = response.headers().get("Content-Type");
        if (contentType == null) {
            // ensuring a default content type
            contentType = "application/json";
        }
        if (isJsonMime(contentType)) {
            return json.deserialize(respBody, returnType);
        } else if (returnType.equals(String.class)) {
            // Expecting string, return the raw response body.
            return (T) respBody;
        } else {
            throw new ApiException(
                    "Content type \"" + contentType + "\" is not supported for type: " + returnType,
                    response.code(),
                    response.headers().toMultimap(),
                    respBody);
        }
```
Since we are consuming a third party API and we can't edit the returned content-type, is there a way to handle different content types or should we provide a custom implementation of the Client?

**Comment by marcoreni** [comment]
Any news about this?

**Comment by HugoMario** [comment]
hey @marcoreni sorry for this long delay. Since this is at template level, i suggest you use a custom template to address your changes. Recently we added a feature that add a capability to use one specify template. So, for this case you just could use `ApiClient.mustache` file in your template dir.
