### ISSUE TITLE
[Spring] Templates and generator already migrated?

### ISSUE THREAD

**Issue by HanMas123** [swagger-api/swagger-codegen-generators#254]
Hi,

currently we are "suffering" from this bug https://github.com/swagger-api/swagger-codegen-generators/issues/103
I was wondering why this fix did not apply to our setup and did some investigations...
We are using the swagger-codegen-maven-plugin having the library option configured to `spring`.
The [SpringCodegen](https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/v3/generators/java/SpringCodegen.java) class is still using Mustache as template engine.
```java
// todo: remove this once handlebar templates for this generator are implemented
    @Override
    protected void setTemplateEngine() {
        templateEngine = new MustacheTemplateEngine(this);
    }
```
It looks like the templates have already been migrated. At least there are template in the handlebar folder https://github.com/swagger-api/swagger-codegen-generators/tree/master/src/main/resources/handlebars/JavaSpring

I would really like to take the fix into our spring codegen setup and I am willing to migrate/help migrating but I am not sure what is left to do to migrate spring code gen from mustache templates to handlebars.

**Comment by wvitte** [comment]
I am running in this bug [#103 ](https://github.com/swagger-api/swagger-codegen-generators/issues/103) as well . I was wondering if there's any way to choose which template engine to use through some configuration?

**Comment by HugoMario** [comment]
hello @HanMas123 @wvitte , this issue has been fixed, so going to close it but please let me know if you still get the issue and i'll help with it.

**Comment by wvitte** [comment]
Thanks looks like it's working. Any idea when v3.0.4 would be out?
