### ISSUE TITLE
[java jaxrs-jersey] Cookie params are never generated

### ISSUE THREAD

**Issue by ahmad-korbesa** [swagger-api/swagger-codegen-generators#259]
If you defined an endpoint that takes a parameter from a cookie, this parameter is not generated.
Hence, both Generated ApiService and ApiServiceImpl are not compilable due to a syntax error in the generated method signature.
the @CookieParam annotation is also not generated.

Example:
.yaml 
> /Product:
    get:
      summary: get a product
      operationId: getProduct
      parameters:
      - in: cookie
        name: sessionid
        schema:
          type: string
      - name: type
        in: query
        required: true
        schema:
          type: string
      - name: name
        in: query
        required: true
        schema:
          type: string

Generated method signature in ProductAPIService:

`public abstract Response getProduct( @NotNull String type, @NotNull String name, /*Missing Parameter Here*/ ,SecurityContext securityContext) throws NotFoundException;`

I added the comment /*Missing Parameter Here*/ to highlight the error

**Comment by nataliaoliveira** [comment]
This is also happening to Spring language.

**Comment by HugoMario** [comment]
Hi, this has been solved with https://github.com/swagger-api/swagger-codegen-generators/pull/549. if you still get the issue please let me know and i'll work on a fix asap.
