### ISSUE TITLE
Remove system properties

### ISSUE THREAD

**Issue by HugoMario** [swagger-api/swagger-codegen-generators#27]
Now that custom arguments have been implemented we can remove the system properties and use custom arguments instead.

**Comment by jmini** [comment]
Have a look at commit dac94a7f402a1fa9392efabb817a07a6d674f626 for an example.

I track this change as new section in my migration how-to: [replace-system-properties-with-custom-arguments](https://github.com/swagger-api/swagger-codegen/wiki/Swagger-Codegen-migration-(swagger-codegen-generators-repository)#replace-system-properties-with-custom-arguments) (feel free to improve it)

**Comment by HugoMario** [comment]
i will, thanks @jmini
