### ISSUE TITLE
[Java] @JsonTypeInfo property not set to Discriminator propertyName

### ISSUE THREAD

**Issue by simon-paradis-jive** [swagger-api/swagger-codegen-generators#291]
The same problem described in https://github.com/swagger-api/swagger-codegen-generators/issues/103 is affecting us with the Java code generator.

Relevant PR's for same issue in Spring codegen:
* https://github.com/swagger-api/swagger-codegen-generators/pull/103/files
* https://github.com/swagger-api/swagger-codegen-generators/pull/273/files

**Comment by HugoMario** [comment]
hey @simon-paradis-jive , this issue has been fixed by #293 . when you have a chance. can you please verify this?

**Comment by simon-paradis-jive** [comment]
@HugoMario Yes, I checked current dev branch yesterday and found it was fixed. Thanks!
