### ISSUE TITLE
having multiple responses in OpenAPI-3.0.0 schema cause faulty generated code 

### ISSUE THREAD

**Issue by ljgw** [swagger-api/swagger-codegen-generators#3]
In swagger 2.0 schemata **produces** was a top level field with mime-types. In OpenApi 3.0.0 schemata media-types are used for this purpose and they are located differently, as **key** for MediaType-Objects in the **content** map. That means that if multiple responses are described, the same media-type can be used as a key in the response content maps.

However, when I try to use this new feature of OpenAPI 3.0.0, my  generated java client code comes out faulty. Using this project to generate java code for the following schema-fragment

```yaml
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
```
results in the following code
```java
    final String[] localVarAccepts = {
      "application/json""application/json"
    };
```
because `hasMore` is incorrectly not added to the 'last *content* in the first *response*'.

Moreover, *application/json* appears twice in the `codegenOperation.produces` ArrayList because while each response yields a `Set` of media-type keys, those sets are combined into a `List` at the `codegenOperation.produces` level.

**Comment by ljgw** [comment]
I made a PR (#4) - my first actually. Unfortunately travis-ci seems to fail, but it looks to me as if that is because it uses a rather old snapshot of swagger-codegen with the wrong version of guava.

`[INFO] Downloading from sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen/3.0.0-SNAPSHOT/swagger-codegen-3.0.0-20180112.231844-20.pom`

**Comment by HugoMario** [comment]
thanks @ljgw , i'll check the travis build issue with guava and then check the PR.

**Comment by HugoMario** [comment]
@ljgw PR [#4](https://github.com/swagger-api/swagger-codegen-generators/pull/4) was already merged. Can you please verify if issue is solved when you have a chance?

**Comment by ljgw** [comment]
Good you remind me, the fix fine in master
