### ISSUE TITLE
CI: integration test problems with latest build

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-codegen-generators#31]
#### Short version:
Rebuild and push the latest `swagger-codegen-generator` in order to fix java.lang.AbstractMethodError in the integration tests

---
#### Background:

The “custom arguments” logic was changed by @HugoMario with following commits:

* https://github.com/swagger-api/swagger-codegen/commit/a547cbba0b89d956c996bc45b1d536516e335f60
* https://github.com/swagger-api/swagger-codegen-generators/commit/3f3d5529ac03e8b8d5c5bf6efe5efe2ed5f11d31

Now the `swagger-codegen-cli` (version `3.0.0-SNAPSHOT`) is broken:

```
Exception in thread "main" java.lang.AbstractMethodError: io.swagger.codegen.languages.java.JavaClientCodegen.readLanguageArguments()Ljava/util/List;
 at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:94)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2g; support was removed in 8.0
```

I think that this is due to a build order problem.

When the commit in repo `swagger-codegen` was pushed, `swagger-codegen-cli` was build, embedding an old version of `swagger-codegen-generators`.

I think that the latest `swagger-codegen-generator-1.0.0-SNPASHOT.jar` was not correctly built and pushed. Probably because the `swagger-codegen` build was not finished.

Now when you build `swagger-codegen` repo, the build is OK, but when the integration tests are executed (the `*.sh` scripts), you get the `AbstractMethodError` exception.

Something is wrong with the build.

---
#### Big picture:

There are cyclic dependencies between the 2 builds of the `swagger-codegen` repo and the `swagger-codegen-generator` repo.

`io.swagger:swagger-codegen-generator:1.0.0-SNAPSHOT` needs `io.swagger:swagger-codegen:3.0.0-SNAPSHOT` from the `swagger-codegen` repository.

And `io.swagger:swagger-codegen-cli:3.0.0-SNAPSHOT` includes `io.swagger:swagger-codegen-generator:1.0.0-SNAPSHOT` from the `swagger-codegen-generators` repository.

When API breaking changes are pushed on the same time in the 2 repos, the continuous integration build is complicated.

**Comment by jmini** [comment]
@HugoMario can you have a look at it?

**Comment by jmini** [comment]
See commit 2fdd9b4c9cabbfb28fe0bc774c1fd84158786ce4 to unlock the build deadlock.

**Comment by HugoMario** [comment]
@jmini this was fixed a couple of hours ago, but let me know if it's still present.
