### ISSUE TITLE
[typescript-angular] "type": "number" references BigDecimal, which is never generated

### ISSUE THREAD

**Issue by wtho** [swagger-api/swagger-codegen-generators#336]
## Issue
When generating (v3.0.5) using
```bash
java -jar \
  -DsupportsES6=true \
  swagger-codegen.jar generate \
  -l typescript-angular \
  -i schema.json \
  -o src/app/generated/
```
and the schema (swagger: 2.0) contains a field

```json
{
  "someField": {
    "type": "number"
  }
}
```
it generates this model:
```ts
import { BigDecimal } from './bigDecimal';

export interface AbonnementTypVO { 
  someField: BigDecimal;
}
```
The problem is, that the file `bigDecimal.ts` is never created.

If the schema contains
```json
{
  "someOtherField": {
    "type" : "integer",
    "format" : "int64"
  }
}
```
it renders `someOtherField: number;`

**Comment by wtho** [comment]
The current workaround from my side was to create `bigDecimal.ts` with
```ts
export type BigDecimal = number;
```
which is quite annoying to do every time.

**Comment by wtho** [comment]
So in JS/TS there are no native solutions for arbitrary-precision decimal arithmetic, but there are e. g. these libraries to achieve it:
* https://github.com/MikeMcl/big.js/
* https://github.com/MikeMcl/bignumber.js/
* https://github.com/MikeMcl/decimal.js/

(At least for `big.js`) There are also corresponding typings in `DefinitelyTyped/types`.

If you don't like to include any of them or implement BigDecimal in JS/TS on swagger's side, it does not make much sense to use some sort of `BigDecimal` in JS/TS. In that case `number` should work just fine.

Are there swagger guidelines on type projections to other languages?

If there is a consent how to handle this and someone points me on the right code locations I'm happy to create a PR. With the current setup and the missing `BigDecimal` this generator is not usable.

**Comment by HugoMario** [comment]
hi @wtho, this issue has been fixed, for latest releases, mapping `BigDecimal` to `number`. going to close issue, but please let me know if you still get the issue.

**Comment by itbrandonsilva** [comment]
I've run into this issue myself. A general model attempts to import `BigDecimal` in a way similar to @wtho initial example does, but the file is missing.

Using the latest build available to me at the moment:
`https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-cli/3.0.17-SNAPSHOT/swagger-codegen-cli-3.0.17-20200123.095202-4-javadoc.jar`.

**Comment by AmazingTurtle** [comment]
@HugoMario is there any difference between swagger-codegen-cli and swagger-codegen-cli-v3? I tried latest, 3.0.18 and unstable on swagger-codegen-cli-v3 and BigDecimal is still poppin' up

**Comment by HugoMario** [comment]
@itbrandonsilva  @AmazingTurtle 
going to check this issue, thanks for letting me know

**Comment by HugoMario** [comment]
hey @itbrandonsilva @AmazingTurtle 

Can you please try with [3.0.20 version](https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.20/swagger-codegen-cli-3.0.20.jar)

**Comment by AmazingTurtle** [comment]
@HugoMario I can confirm, BigDecimal is gone by now with the 3.0.20 version. Thanks for the fix
