### ISSUE TITLE
Java: Property names are not sanitized

### ISSUE THREAD

**Issue by amathew121** [swagger-api/swagger-codegen-generators#378]
**Description**

The problem is that property @odata.context is mapped to a member field called `@odataContext` which is not a valid java variable name

**Swagger-codegen version**
3.0.8

**Swagger declaration file content or url**
```
openapi: 3.0.1
info:
  title: A dummy title
  version: 1.0.0

paths:
  /my/endpoint:
    get:
      summary: Returns an object 
      operationId: getMyObject
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dummy" 
components:
  schemas:
    Dummy:
      type: object
      properties:
        '@odata.context':
          type: string
```

**Output Java code:**
```
public class Dummy {

  @SerializedName("@odata.context")
  private String @OdataContext = null;
```

**Suggest a fix/enhancement**

The following regular expression is used to sanitize the property name. 
`\\W-[\\$]` 

This does not work as intended in java, and should be changed to 
`[\\W&&[^$]]` - A non word character except $

**Comment by hejcz** [comment]
Any news on this issue?
