### ISSUE TITLE
NPE parsing `oneOf` schema that is not a ref

### ISSUE THREAD

**Issue by chris-prop** [swagger-api/swagger-codegen-generators#416]
If schema is defined as `oneOf` and an option is not a reference, a NullPointerException is generated.

This issue was also reported in https://github.com/swagger-api/swagger-codegen/issues/9541

**Comment by frantuma** [comment]
Thanks for reporting and analyzing this! It has been fixed in #415, closing ticket, please reopen if you're still experiencing issues
