### ISSUE TITLE
Create template for Micronaut-based java server side application

### ISSUE THREAD

**Issue by franz-see** [swagger-api/swagger-codegen-generators#429]
Add the ability to create micronaut-based server side java application given an open api spec.

**Comment by franz-see** [comment]
FYI: I have created a standalone project for now so that I can use it myself without waiting for it to be merged into `swagger-codegen-generators` :) 

https://github.com/swagger-api/swagger-codegen-generators/issues/429

**Comment by HugoMario** [comment]
hey @franz-see ping me anytime you need a PR for being merge :)

**Comment by HugoMario** [comment]
changes have been merged, closing this out.

**Comment by mbm56767** [comment]
> @franz-see i tried your PR and found a few errors:
> 
> using [this yaml document](https://gist.githubusercontent.com/danielflower/5c5ae8a46a0a49aee508690c19b33ada/raw/b06ff4d9764b5800424f6a21a40158c35277ee65/petstore.json)
> 
> it is common to say in many operations' annotations a double comma: `,,` like this:
> 
> ```java
> @Operation(summary = "Create user", operationId = "createUser", description = "This can only be done by the logged in user.", tags={ "user", })
>     @ApiResponse(responseCode = "200", description = "successful operation")
>     @Post(value = "/user",,
>         consumes = { "application/json" }
>         )
>     default Single<HttpResponse<Void>> createUser(
>           @Parameter(description = "Created user object", required = true ) @Valid @Body User body  
>   ) {
>         return Single.fromCallable(() -> {
>             throw new UnsupportedOperationException();
>         });
>     }
> ```
> 
> `Authorization` and `AuthorizationScope` are not imported. About this points i wanted to ask you if you have planned use security from micronaut too?
> 
> It would be nice to have on README file a guide about how to run the generated code.
> 
> Let me know what you think about it, and if you need help, please give me write access on your fork and i will be really glad to help :)

I am still facing the issues mentioned here.
many operations' annotations a double comma: ,,
Authorization and AuthorizationScope are not imported
due to these issues, i am not able run the generated micronaut code .

Can someone help me here?
