### ISSUE TITLE
[Spring] process option `useOas2` in spring templates as done in java ones

### ISSUE THREAD

**Issue by frantuma** [swagger-api/swagger-codegen-generators#444]

**Comment by reta** [comment]
Hi @frantuma, afaik Spring integration (Springfox, https://github.com/springfox/springfox) still has not release OAS 3.0 support (3.0.0 is still in snapshot for quite a while), so the only option for now is OAS 2.0. I am wondering if you have other ideas in mind, I would be happy to help out. Thanks!

**Comment by rockxwre** [comment]
In case of OAS 3.0, maybe [springdoc-openapi](https://github.com/springdoc/springdoc-openapi) can be used as an alternative for Springfox? See also https://www.dariawan.com/tutorials/spring/documenting-spring-boot-rest-api-springdoc-openapi-3/ for an example?
In the meantime, some extra documentation would be useful. It took me a long time to figure out OAS 3 was not supported for Spring.

**Comment by rrockx-trifork** [comment]
I created a [branch](https://github.com/rrockx-trifork/swagger-codegen-generators/commits/issue-444) which supports OAS3 for (only) Spring Boot using [springdoc-openapi](https://github.com/springdoc/springdoc-openapi). By default OAS3 is used. If OAS2 needed, use `--use-oas2` option.

@reta : what do you think about [this solution](https://github.com/rrockx-trifork/swagger-codegen-generators/commit/9e1c9b4a76e22917929352e372ba04579324259a)?

**Comment by reta** [comment]
@rrockx-trifork it looks good in fact.  It is a bit difficult to understand what are the consequences  to switch from `spring-fox` to `springdoc-openapi` (I have never used latter), but apparently this is the best bet at the moment. Thank you!

**Comment by rrockx-trifork** [comment]
@reta

> @rrockx-trifork it looks good in fact.

Great!

> It is a bit difficult to understand what are the consequences to switch from `spring-fox` to `springdoc-openapi` (I have never used latter), but apparently this is the best bet at the moment. 

Since [it is still unclear](https://github.com/springfox/springfox/issues/3070) when Springfox will support OAS3 schemas, I think this alternative will do just fine.

> Thank you!

Created a (draft) PR: #618

**Comment by pynivollet** [comment]
Hello, I think I need this modification for my project, because for now I am not able to use OpenApi3 specification when I generate code with codegen from my spring-boot project. Do we have any idea of when it will be done? Thanks
