### ISSUE TITLE
[Kotlin] OAS3 date-time includes timezone. Generator still uses LocalDateTime

### ISSUE THREAD

**Issue by tobias-** [swagger-api/swagger-codegen-generators#472]
According to example and the format referenced in
https://swagger.io/docs/specification/data-models/data-types/#string

The following line should be changed to ~`java.time.ZonedDateTime`~ `java.time.OffsetDateTime`:
https://github.com/swagger-api/swagger-codegen-generators/blame/master/src/main/java/io/swagger/codegen/v3/generators/kotlin/AbstractKotlinCodegen.java#L157

**Comment by tobias-** [comment]
Mea culpa. It should of course be the same as what the Java Codegen uses: `java.time.OffsetDateTime`.

**Comment by tobias-** [comment]
`date`/`Date` should use LocalDate as well

**Comment by HugoMario** [comment]
thanks @tobias- for reporting this. if you are willing/available to propose a PR, i could help with reviewing and PR
