### ISSUE TITLE
[Question] Should we create a openapi3.0 -> openapi2.0 generator first?

### ISSUE THREAD

**Issue by shuoli84** [swagger-api/swagger-codegen-generators#48]
Though the specification 3.0 itself is released, ecosystem not involved rapidly enough. I just spend a couple of days to create a 3.0 specification for our 100+ api endpoints, then sadly learned that python, swift code generators are not implemented yet. 

Before our generators catch up, is it a practical solution to first create a 3.0 -> 2.0 generator?

**Comment by MikeRalphson** [comment]
There may be ideas you can take from https://github.com/Mermade/openapi-codegen/blob/master/lib/orange/downconvert.js - which is derived from https://github.com/Orange-OpenSource/angular-swagger-ui/blob/master/src/scripts/modules/openapi3-converter.js

License is MIT.

**Comment by shuoli84** [comment]
In case someone have problem with running node, here is a python version:
https://gist.github.com/shuoli84/3e61b3f1af3ed0c71282462b317fa2ea

**Comment by shuoli84** [comment]
Update: Successfully generated python and swift client using this approach. 💃💃💃

**Comment by jmini** [comment]
I have also some java code to do a v3 to v2 conversion somewhere, but it might be incomplete. If someone is interested, just ask, I can publish it somewhere.

@shuoli84: I could migrate the codegen to v3, but then I will not be able to juge if the result is correct or not. Would be interested in doing some tests and providing me some help if I migrate the codegen to v3?

**Comment by shuoli84** [comment]
@jmini verification of correctness indeed is one of the most important thing. I guess a v3 -> v2 -> v3'2 then compare v'2 and v3 could be a start.
