### ISSUE TITLE
JavaClientCodegen causes NPEs due to object-in-map modification

### ISSUE THREAD

**Issue by abassouk** [swagger-api/swagger-codegen-generators#495]
Specifically, this code: https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/v3/generators/java/JavaClientCodegen.java#L537-L540

This code modifies entries that were added in `byParent` on line 520, and is retrieved on line 528. As the entries compute their hashCode dynamically, the new entries are no longer accessible as their hashCode is now different, and this leads to NPEs.

Resolve via iterating through `entrySet` instead of `keySet`.

**Comment by frantuma** [comment]
Thanks for reporting and investigating! fixed in #496
