### ISSUE TITLE
Migrate guava logic to java 8

### ISSUE THREAD

**Issue by HugoMario** [swagger-api/swagger-codegen-generators#5]
There is an error with dependency classes from guava. But instead fixing it with maven dependency declaration, let's take this chance to migrate that logic to Java 8.

**Comment by jmini** [comment]
At the moment there is a compile dependency on Guava:

* In [AbstractJavaCodegen#sanitizePackageName(String)](https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/languages/java/AbstractJavaCodegen.java#L1098) (line 1098) you are using guava perform this check: `Strings.isNullOrEmpty(packageName)`
* In [DefaultCodegenConfig.removeNonNameElementToCamelCase(String, String)](https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/languages/DefaultCodegenConfig.java#L2883) (line 2883) both `com.google.common.base.Function` and `com.google.common.collect.Lists` are used.

@HugoMario: I guess you mention rewritting the code for the second use case.

---

In the mean time I had a look a the dependencies tree, guava `15.0` is already a `test` scope dependency, so I added the same version a `compile` dependencies.

```
<dependency>
	<groupId>com.google.guava</groupId>
	<artifactId>guava</artifactId>
	<version>15.0</version>
</dependency>
```

**Comment by jmini** [comment]
I think the guava version included in the last released version of this project (`1.0.0-rc0`) was guava `23.0`.

The guava dependency is no longer present in the last SNAPSHOT version used in the current dependencies.

See also my analysis (with screenshot) in #4.

**Comment by jmini** [comment]
I have missed usage of `com.google.common.collect.LinkedListMultimap` in `JavaClientCodegen`. Not sure what you want to do about it.

**Comment by HugoMario** [comment]
Well, the idea is remove any `guava` dependency

**Comment by jmini** [comment]
To replace `LinkedListMultimap` with java8 code, I found this blog post: http://fahdshariff.blogspot.fr/2017/07/java-8-multimaps.html

Second pull request: #7.

**Comment by HugoMario** [comment]
Travis has a success build now, but it seems there is a config error.
https://api.travis-ci.org/v3/job/338265006/log.txt
