### ISSUE TITLE
JaxRS: Generate code for Swagger v3

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-codegen-generators#50]
**PREREQUISITE:** following PR needs to be merged:
* https://github.com/swagger-api/swagger-codegen/pull/7854
* https://github.com/swagger-api/swagger-codegen/pull/7904

---

JaxRS generators were introduced here with #29 (and with the follow up tasks #38, #36 and #39). JaxRS Client CFX generator was introduce with #47. JaxRS examples in the [`samples/`](https://github.com/swagger-api/swagger-codegen/tree/3.0.0/samples/) folder are going to be updated with https://github.com/swagger-api/swagger-codegen/pull/7854.

As indicated in the help description message, the mentioned generators still generate code for Swagger v2:

> WORK IN PROGRESS: generated code depends from Swagger v2 libraries

One example of the impact:

When you run `mvn clean package jetty:run` inside the [`samples/server/petstore/jaxrs/jersey2/`](https://github.com/jmini/swagger-codegen/tree/patch-9/samples/server/petstore/jaxrs/jersey2)  folder and then call `http://localhost:8080/v2/swagger.yaml`, you obtain:

```
swagger: "2.0"
info:
  ...
host: "petstore.swagger.io:80"
basePath: "/v2"
tags:
...
schemes:
- "http"
paths:
  /another-fake/dummy:
    patch:
      ...
  /fake/outer/boolean:
    post:
      tags:
      - "fake"
      summary: ""
      description: "Test serialization of outer boolean types"
      operationId: "fakeOuterBooleanSerialize"
      consumes:
      - "*/*"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "body"
        description: "Input boolean as post body"
        required: false
        schema:
          type: "boolean"
      responses:
        200:
          description: "Output boolean"
          schema:
            type: "boolean"
  /fake/outer/composite:
    post:
      ...
  /fake/outer/number:
    ...
```

The big next step for the JaxRS generators will be to generate code that will be using Swagger v3 artefacts. Then the page to call to get the spec will be `http://localhost:8080/v2/openapi.yaml`

---

I did not look at all the details yet, but I think the main point is to replace:

    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-jersey2-jaxrs</artifactId>
      <version>1.5.15</version>
    </dependency>

With:

    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-jaxrs2</artifactId>
      <version>2.0.0-SNAPSHOT</version>
    </dependency>

The `swagger-samples` repository on branch `2.0` contains valuable examples that already works with  Swagger v3. See: https://github.com/swagger-api/swagger-samples/tree/2.0/

---

I will work on this as soon as the blocking PR are merged.

**Comment by jmini** [comment]
Now the `2.0.0` was released I will definitivelly use this version for the generated code. It is much better than a SNAPSHOT.

I also think that I will need to drop `jersey1` library support. I do not think that this is a big deal.

**Comment by anirtek** [comment]
@jmini @HugoMario @spidermaninalaska how can I get this to work for jakarta namespace? I am using swagger-core 2.1.9
