### ISSUE TITLE
Java generators and 'samples/' folder

### ISSUE THREAD

**Issue by jmini** [swagger-api/swagger-codegen-generators#52]
I was working on #51 and to ensure that my change will not break anything, I have checked the current status of the java generators in `swagger-codegen` repository in the `samples/` folder on the 3.0.0 branch. I use version `1.0.0-SNAPSHOT` of the `swagger-codegen-generators` generators.

The scripts needs to be fixed and the examples needs to be generated again.

I will report here what needs to be addressed.

**Comment by jmini** [comment]
`bin/java-petstore-jersey2-java6.sh`:

Following Error during code generation:

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'Cat'
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:728)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.jknack.handlebars.HandlebarsException: /v2/Java/pojo.mustache:142:107: java.lang.ClassCastException: java.lang.String cannot be cast to io.swagger.codegen.VendorExtendable
    /v2/Java/pojo.mustache:142:107
	at io.swagger.codegen.handlebars.helpers.ExtensionHelper.apply(ExtensionHelper.java:11)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at ...
```

The `java` command in the script is commented. `samples/client/petstore/java/jersey2-java6` will not be updated until the error is fixed.

**Comment by HugoMario** [comment]
got it, i'll work on it

**Comment by jmini** [comment]
`bin/java-petstore-feign.sh`

When the code is generated, if you run `mvn verify` in  `{swagger-codegen repo}/samples/client/petstore/java/feign/` you get this compile error:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /***/swagger-codegen/samples/client/petstore/java/feign/src/main/java/io/swagger/client/auth/OAuth.java:[192,36] method references are not supported in -source 1.7  (use -source 8 or higher to enable method references)
[ERROR] /***/swagger-codegen/samples/client/petstore/java/feign/src/main/java/io/swagger/client/auth/OAuth.java:[193,27] lambda expressions are not supported in -source 1.7  (use -source 8 or higher to enable lambda expressions)
```

Solution: config file `bin/java-petstore-feign.json` will be modified to require java 8.

**Comment by jmini** [comment]
@HugoMario: I will push a change with the corrected version of the script

**Comment by jmini** [comment]
See Pull Request: https://github.com/swagger-api/swagger-codegen/pull/7932

@HugoMario: 
I think we should merge this (if the CI is Ok) and then start to work on the separated issues described here.
If you want I can have a look at it when I am working on #51.
Can you please confirm how you want to work on this?

**Comment by jmini** [comment]
I had to comment:
* `bin/java-petstore-okhttp-gson.sh`
* `bin/java-petstore-okhttp-gson-parcelable.sh`

Because of this error when trying to compile the examples:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-petstore-okhttp-gson: Compilation failure: Compilation failure: 
[ERROR] /***/swagger-codegen/samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/JSON.java:[24,19] package io.gsonfire does not exist
[ERROR] /***/swagger-codegen/samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/JSON.java:[25,19] package io.gsonfire does not exist
[ERROR] /***/swagger-codegen/samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/JSON.java:[60,9] cannot find symbol
[ERROR]   symbol:   class GsonFireBuilder
[ERROR]   location: class io.swagger.client.JSON
[ERROR] /***/swagger-codegen/samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/JSON.java:[62,51] cannot find symbol
[ERROR]   symbol:   class TypeSelector
[ERROR]   location: class io.swagger.client.JSON
[ERROR] /***/swagger-codegen/samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/io/swagger/client/JSON.java:[60,43] cannot find symbol
[ERROR]   symbol:   class GsonFireBuilder
[ERROR]   location: class io.swagger.client.JSON
```

**Comment by jmini** [comment]
@HugoMario : thank you for the merge of https://github.com/swagger-api/swagger-codegen/pull/7932. Do you want to close this issue or keep it open until the issues have bin fixed?

**Comment by HugoMario** [comment]
I think we should keep it open for now.

**Comment by jmini** [comment]
I have a solution for `java-petstore-jersey2-java6`, I will post a PR later.

**Comment by jmini** [comment]
I have started a PR to fix the issues listed here: #53

**Comment by jmini** [comment]
I was not able to reproduce the problem I had with:

* `bin/java-petstore-okhttp-gson.sh`
* `bin/java-petstore-okhttp-gson-parcelable.sh`

I have opened a PR to check if it work on the CI server: https://github.com/swagger-api/swagger-codegen/pull/7939 (we can use this PR to update all examples when #53 is merged).

**Comment by jmini** [comment]
Now that #53 is merged, the last point is the problem mentioned when script `bin/java-petstore-google-api-client.sh` is executed (see my previous comment).
