### ISSUE TITLE
Discriminator not set correctly for ComposedSchema 

### ISSUE THREAD

**Issue by aaronjwhiteside** [swagger-api/swagger-codegen-generators#527]
In https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/v3/generators/DefaultCodegenConfig.java#L1322-L1323

The lines 
```
                            codegenModel.discriminator = schema
                                    .getDiscriminator();
```

should be

```
                            codegenModel.discriminator = innerModel
                                    .getDiscriminator();
```

The point of the loop is to check the innerModels for Discriminators, it looks like a typo/copy-n-paste error

**Comment by frantuma** [comment]
Thanks for reporting and investigating! Fixed in #556
