### ISSUE TITLE
[csharp] First entry in enum is not emitted unless EmitDefaultValue is set to true

### ISSUE THREAD

**Issue by ciresh** [swagger-api/swagger-codegen-generators#539]
If you have a definition like:
```
        eventId:
          type: string
          enum:
            - available
            - pending
            - sold
```
the generated c# code will look like:
```
[JsonConverter(typeof(StringEnumConverter))]
        public enum EventIdEnum
{
    /// <summary>
    /// Enum Available for value: available
    /// </summary>
    [EnumMember(Value = "available")]
    Available = 0,
    /// <summary>
    /// Enum Pending for value: pending
    /// </summary>e
    [EnumMember(Value = "pending")]
    Pending = 1
    /// <summary>
    /// Enum Sold for value: sold
    /// </summary>
    [EnumMember(Value = "sold")]
    Sold = 2        }
```
The value `available` will never be emitted unless you set EmitDefaultValue=true. The reason is in c# enums are stored as integers and the default value for an integer is 0.

swagger-codegen 2.x didn't have this problem because it started the enums at 1. The 2.x version uses mustache's {{-index}} in the template to generate the enum integer value and {{-index}} starts at 1. The 3.x release uses handlebar's {{@index}} which starts a 0. The simple fix is to change the handlebar templates to use {{@index_1}} which starts a 1.

**Comment by frantuma** [comment]
Thanks for reporting and investigating! fixed in #558
