### ISSUE TITLE
Nested objects are not supported for `queryParams`

### ISSUE THREAD

**Issue by chriszo111** [swagger-api/swagger-codegen-generators#541]
We needed support for nested objects, as we need to handle `queryParams` such as `page[size]=1&page[number]=1` for our API. Our solution was to iterate over the `object` directly in the `api.mustache` file because we could not figure out where else we could cover the case. 

Any ideas on that? Or is there a better way to support nested objects in `queryParams`?

But this causes unwanted problems, like we would have to maintain every language separately, think about a way to maintain the fork properly, ...

### Code changes

- [`api.mustache`](https://github.com/swagger-api/swagger-codegen-generators/blob/cb6d0340f88d2eb2fe7b3e6f53d1344851db9f84/src/main/resources/handlebars/python/api.mustache#L160)

```diff
query_params = []
{{#queryParams}}
        if '{{paramName}}' in params:
-            query_params.append(('{{baseName}}', params['{{paramName}}'])){{#isListContainer}}  # noqa: E501
-            collection_formats['{{baseName}}'] = '{{collectionFormat}}'{{/isListContainer}}  # noqa: E501
-{{/queryParams}}
+            if type(params['{{paramName}}']).__name__ is 'Page':
+                params_dict = params['page'].to_dict()
+                for subParam in params_dict.keys():
+                    query_params.append(('{{baseName}}[' + subParam + ']', params_dict[subParam]))
+            else: 
+                query_params.append(('{{baseName}}', params['{{paramName}}'])){{#isListContainer}}  # noqa: E501
+                collection_formats['{{baseName}}'] = '{{collectionFormat}}'{{/isListContainer}}  # noqa: E501
+{{/queryParams}}
```

Thanks for any help :)!

**Comment by louisl** [comment]
There's a discussion you might find interesting about how the spec can/could handle this here: https://github.com/OAI/OpenAPI-Specification/issues/1706#issuecomment-553455595

**Comment by chriszo111** [comment]
Progress in this area, not supporting `deepObjects` yet though https://github.com/nemtech/symbol-openapi/pull/91

**Comment by HugoMario** [comment]
covered by https://github.com/swagger-api/swagger-codegen-generators/pull/961
However some generators may still need changes to support this.
