### ISSUE TITLE
Template Property isResponseFile is not set

### ISSUE THREAD

**Issue by cjanz** [swagger-api/swagger-codegen-generators#547]
First of all thank you for providing this great library 🙏🏻

We are using Swagger CodeGen v3 with the `typescript-angular` template to generate code for our APIs. It works great except for API operations that return Blobs/Files.

The problem is that the `responseType` Property is not set to `blob` for the Angular HttpClient call. 

I have seen that the template has support for it by setting the correct property when `isResponseFile` is truthy for the operation: https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/resources/handlebars/typescript-angular/api.service.mustache#L329-L331

But it seems that `isResponseFile` is not set for the `CodegenOperation` in any of the Java classes that build the model. In Swagger CodeGen V2 the `isResponseFile` flag is set here: https://github.com/swagger-api/swagger-codegen/blob/d3355dbda327e70e80551dfd9b632a45dc6c66e4/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L2207

If you need further information or help please let me know.

**Comment by cjanz** [comment]
In the meanwhile we have switched to OpenAPI Generator (https://github.com/OpenAPITools/openapi-generator). The `typescript-angular` generator in this project does not have this issue and generates correct code for blob results.

So, I'm closing this issues 🥳

**Comment by glebmachine** [comment]
Damn
