### ISSUE TITLE
Abnormal random enumerators generation in c#

### ISSUE THREAD

**Issue by PaoloCifelli** [swagger-api/swagger-codegen-generators#550]
When we generate classes that contain references to enums randomly the enums are not generated correctly: this could be solved by modifying
in class AbstractCSharpCodegen at line 438
` var.allowableValues = refModel.allowableValues;`
with
`var.allowableValues = new HashMap<>(refModel.allowableValues);`
Thanks

**Comment by frantuma** [comment]
Thanks for reporting this! fixed in #561
