### ISSUE TITLE
Micronaut generate API class and not interface

### ISSUE THREAD

**Issue by lancerbh** [swagger-api/swagger-codegen-generators#629]
The API is being generated as a class and not an interface. Is it correct or should it be an interface with default methods? Or is there any justification for this?

https://github.com/swagger-api/swagger-codegen-generators/blob/5a12700e2d5ba9bd484069e7e99fb0411a914934/src/main/resources/handlebars/JavaMicronaut/api.mustache#L31

**Comment by HugoMario** [comment]
Hi @lancerbh, the api template was added as a class, we could add an option to write as interface although. Any help/idea is always welcome :)

**Comment by shourien** [comment]
Hi @HugoMario 
What the was the reason to change the original interface to a class? I see that it was originally submitted as an interface but changed under this [Commit](https://github.com/swagger-api/swagger-codegen-generators/pull/476/commits/59cf2a802790eac7dad6fcef54c692e7f6c92c74#diff-bb30d496115228e84bb6ff2ca303df8a)

**Comment by HugoMario** [comment]
@shourien 

the fact that there were methods with body inside the template, now i realize that it would have been better just to add the `default` keyword to methods.

if you are willing to change that i would help you with merging.

**Comment by shourien** [comment]
@HugoMario I have checked out master code and made the changes accordingly + added couple of unit tests as well. How do I create branch to raise a pull request?

**Comment by HugoMario** [comment]
@shourien 
https://jarv.is/notes/how-to-pull-request-fork-github/ i think this can guide you

**Comment by shourien** [comment]
@HugoMario I have raised a pull request and its ready for review.

**Comment by shourien** [comment]
@lancerbh @HugoMario I have tested this from my end on 3.0.21 version for micronaut and works fine for this ticket

```
@Singleton
@Introspected(classes = String.class)
class PetStoreController implements PetApi {
    @Override
    public Single<HttpResponse<Void>> sample(String petId) {
        return Single.just(HttpResponse.ok());
    }
}
```

**Comment by HugoMario** [comment]
thanks for update @shourien 

Let's close this!
