### ISSUE TITLE
Fix for allOf discriminator issue breaks oneOf discriminator generation

### ISSUE THREAD

**Issue by trohrberg** [swagger-api/swagger-codegen-generators#654]
A couple of days ago, I realized that my project using the Swagger Codegen does not work anymore when using the current release version of Swagger Codegen. The problem is that, for a oneOf discriminator mapping, the corresponding Type-Info-Annotation is now missing in the POJO model classes:

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "typ", visible = true )
@JsonSubTypes({
}}

After investigating the issue further, I realized that the changes for PR #620 introduced a change which breaks that part of the code generation. Thus, I am able to provide a PR to fix that problem shortly.

**Comment by HugoMario** [comment]
fixed wth #773
