### ISSUE TITLE
Wrong authMethods is inserted for the Operations

### ISSUE THREAD

**Issue by nirumand** [swagger-api/swagger-codegen-generators#672]
The Codegen for javaSpring inserts the authMethods from the securitySchema definition instead of the operation level security description:

Class: io.swagger.codegen.v3.DefaultGenerator

method: processOperation

               Map<String, SecurityScheme> authMethods = getAuthMethods(securities, securitySchemes);
                if (authMethods == null || authMethods.isEmpty()) {
                    authMethods = getAuthMethods(globalSecurities, securitySchemes);
                }

**Comment by HugoMario** [comment]
hey @nirumand, sorry for delay reply

i tested this and it's working fine, maybe it was fixed on recent releases. Going to close it for now, but if you still get this issue, please let me know and i work on it asap.
