### ISSUE TITLE
Micronaut codegen does not allow us to remove specific supporting files

### ISSUE THREAD

**Issue by radarsh** [swagger-api/swagger-codegen-generators#688]
Micronaut codegen seems to generate a lot of supporting files such as READMEs, pom files, main class, etc which is not always useful. 

https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/v3/generators/java/MicronautCodegen.java#L167-L173

For instance I use Gradle as a build tool and have a separate main class and the only reason I use the codegen is to generate controller stubs. I'm sure there will be similar reasons for other people too.

Is there any way to customise what gets included in the supporting files list?

**Comment by HugoMario** [comment]
hey @radarsh , if you are working with codegen CLI i could add an option to skip supporting files on generation

**Comment by radarsh** [comment]
@HugoMario I'm actually using Gradle and the codegen classes directly. Is there an equivalent here?

```
task swagger {
    inputs.file('api.yml')
    outputs.dir(file("${buildDir}/generated/sources"))
    doLast {
        new DefaultGenerator().opts(
            new CodegenConfigurator(
                inputSpec: file('api.yml').text,
                outputDir: "${buildDir}/generated/sources",
                lang: 'micronaut',
                additionalProperties: [
                    dateLibrary: 'java8',
                    invokerPackage: 'com.example.todo',
                    configPackage: 'com.example.todo.config',
                    apiPackage: 'com.example.todo.api',
                    modelPackage: 'com.example.todo.api.model'
                ]
            ).addDynamicProperty('sourceFolder', 'src/swagger/java').toClientOptInput()
        ).generate()
    }
}
```

**Comment by HugoMario** [comment]
seems we can go with adding the option as `AdditionalProperties`. that would work everywhere

**Comment by radarsh** [comment]
Ideally an option to individually select supporting files would be desirable as some people might want a few of them but skipping them entirely is fine with me as well.

**Comment by HugoMario** [comment]
on #689 i accomplish the feature, so, going to close this one.

**Comment by HugoMario** [comment]
The additional property to skip support files generation is `skipSupportFiles`

it can be used in CLI as:

```
 --additional-properties skipSupportFiles=true
```
