### ISSUE TITLE
codegenerator for OAS 3.0 for nodejs

### ISSUE THREAD

**Issue by I302609** [swagger-api/swagger-codegen-generators#708]
Hi,
In my pom i have a dependency for 1.0.20 for swagger. For 2.0 I have codegen dependencies separately.

swagger-codegen-generators-1.0.20

 
When I try to generate the code for nodejs I get the below error

[SPACES][SERVER_ERROR]:Error in the request: Can't load config class with name nodejs-server Available: dynamic-html
html
html2
java
jaxrs-cxf-client
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-di
jaxrs-resteasy-eap
jaxrs-resteasy
spring
openapi
openapi-yaml
kotlin-client
kotlin-server
php
swift3
swift4
typescript-angular

Anyhelp is appreciated..

**Comment by I302609** [comment]
final CodegenConfigurator configurator = new CodegenConfigurator()
        .setLang("nodejs-server")
        .setInputSpec(opts.getSpec().toPrettyString())
        .setOutputDir(outputFolder);
    clientOptInput = configurator.toClientOptInput();
    } catch(RuntimeException e) {
      e.printStackTrace();
    }

**Comment by I302609** [comment]
@HugoMario  saw some inputs from you .. Can you please help here

**Comment by I302609** [comment]
Dependencies in my pom
<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-codegen</artifactId>
			<version>2.4.11</version>
			<exclusions>
 				<exclusion>
 					<groupId>org.slf4j</groupId>
 					<artifactId>slf4j-ext</artifactId>
 				</exclusion>
 			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.6.0</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-models</artifactId>
			<version>1.6.0</version>
		</dependency>
			<dependency>
    <groupId>io.swagger.codegen.v3</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>3.0.20</version>
</dependency>
	<dependency>
	<groupId>io.swagger.parser.v3</groupId>
	<artifactId>swagger-parser</artifactId>
	<version>2.0.20</version>
</dependency>
		
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-parser</artifactId>
			<version>1.0.49</version>
			<exclusions>
 				<exclusion>
 					<groupId>org.slf4j</groupId>
 					<artifactId>slf4j-ext</artifactId>
 				</exclusion>
 			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-utils</artifactId>
		</dependency>

**Comment by HugoMario** [comment]
hey @I302609 
try to use:
```
io.swagger.codegen.v3
swagger-codegen
3.0.20
```
instead

```
io.swagger
swagger-codegen
2.4.11
```

**Comment by I302609** [comment]
Thanks @HugoMario  for the time actually the need of my project 
is that i need to generate stub for both 2.0 and 3.0
So for 2.0 I'm using io.swagger
swagger-codegen
2.4.11

and for 3.0
I'm using

	<dependency>
    <groupId>io.swagger.codegen.v3</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>3.0.20</version>
</dependency>

After your suggestion I removed the dependency   <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>3.0.20</version>

and instead have put

**Comment by I302609** [comment]
@HugoMario  thanks alot the suggestion worked..
