### ISSUE TITLE
JavaClientCodegen.java:535 refers to missing resource "/arguments/java.yaml"

### ISSUE THREAD

**Issue by kalexmills** [swagger-api/swagger-codegen-generators#71]
Also, I am not sure that the leading '/' will work on all platforms.

Pushed by https://github.com/swagger-api/swagger-codegen-generators/commit/3f3d5529ac03e8b8d5c5bf6efe5efe2ed5f11d31

@HugoMario maybe take a look?

**Comment by kalexmills** [comment]
https://github.com/swagger-api/swagger-codegen-generators/commit/3f3d5529ac03e8b8d5c5bf6efe5efe2ed5f11d31

**Comment by HugoMario** [comment]
thanks @kalexmills, going to verify this on windows.
