### ISSUE TITLE
[Java][retrofit2] IsResponseFile template variable is not set by generator

### ISSUE THREAD

**Issue by UnHumbleBen** [swagger-api/swagger-codegen-generators#715]
In version 2, `isResponseFile` is set here:
https://github.com/swagger-api/swagger-codegen/blob/d3355dbda327e70e80551dfd9b632a45dc6c66e4/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L2207

In version 3, this file is deleted from the swagger-codegen 3.0 branch by [this commit](https://github.com/swagger-api/swagger-codegen/commit/26354f362235b5d3e5d2b8271d287ad48e632057), with the commit message claiming that the file will be moved to this repository, [but there is no replacement in this repository](https://github.com/swagger-api/swagger-codegen-generators/search?q=filename%3ADefaultCodegen.java&unscoped_q=filename%3ADefaultCodegen.java). This is similar to issue #547 but the user who asked that issue "resolved" the problem by abandoning swagger-codegen and switching to [openapi-generator](https://github.com/OpenAPITools/openapi-generator). Can a fix be provided in this repository? Otherwise, I might also have to switch to openapi-generator

**Comment by HugoMario** [comment]
The file you are looking for was renamed to [DefaultCodegenConfig](https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/v3/generators/DefaultCodegenConfig.java)

You can use this codegen, switch to another one, use both, all are valid and respectful decisions. Don't feel yourself to be forced, we don't want that :)

**Comment by UnHumbleBen** [comment]
@HugoMario The `isResponseFile` variable is not set in that file either.

**Comment by HugoMario** [comment]
it's used as a key/val in a map:

https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/v3/generators/DefaultCodegenConfig.java#L2020

but on template it can be called same way:
```
{{#isResponseFile}} ... {{/isResponseFile}}
```

**Comment by UnHumbleBen** [comment]
@HugoMario Thanks for the explanation. I had a misunderstanding before. I thought that the `isResponseFile` was not being set at all, but it actually was, only its value was `false`.  Now I am confused about why `isResponseFile` is required to be `true` to use `ResponseBody` in the `retrofit2` template?
https://github.com/swagger-api/swagger-codegen-generators/blob/d8e6554909b4d9a5cf357820f54795056f457cb5/src/main/resources/handlebars/Java/libraries/retrofit2/api.mustache#L60

Can you explain what it means for `isResponseFile` to be `true`? I tried following the steps in [the wiki] but there is no explanation for what the variable means, or why it would need to be `true` to use the `ResponseBody` type.

**Comment by HugoMario** [comment]
no so familiar with retrofit2 framework, this code was ported from swagger-codegen repo to work with codegen v3.

I guess `ResponseBoby` is a good way for file type schemas handling. Do you think there is another/better way?

**Comment by RodolpheNivelet** [comment]
Hello,

Is version 3 you need to add `x-is-file: true` to your swagger documentation. This is barely documented so it took me 1 day to figure this out.

Now my response looks like this : 
```json
"responses": {
    "default": {
        "description": "default response",
        "x-is-file": "true",
        "content": {
            "application/octet-stream": {
                "schema": {
                    "type": "string",
                    "format": "binary"
                }
            }
        }
    }
}
```

Bonus, is you are using swagger annotation in spring, you can basically copy paste this line on your end-point :
```java
@ApiResponse(content = @Content(schema = @Schema(type = "string", format = "binary")), extensions = {@Extension(properties = {@ExtensionProperty(name = "x-is-file", value = "true")})})
```

Hope it helped 😁
