### ISSUE TITLE
JavaJAXRSSpecServerCodegen ignores apiPackage and modelPackage property

### ISSUE THREAD

**Issue by eithafol** [swagger-api/swagger-codegen-generators#76]
JavaJAXRSSpecServerCodegen processOpts() method calls super.processOpts() which has already set  apiPackage and modelPackage before JavaJAXRSSpecServerCodegen writes them again to 

        apiPackage = "io.swagger.api";
        modelPackage = "io.swagger.model";

This overwrites any additioinalProperty set for these variables.

**Comment by knap1930** [comment]
+1

**Comment by frantuma** [comment]
Fixed in #560
