### ISSUE TITLE
Connexion version incorrect in requirements.txt

### ISSUE THREAD

**Issue by jstockdi-marstone** [swagger-api/swagger-codegen-generators#780]
See: https://github.com/swagger-api/swagger-codegen/issues/10192

In order to run the "python-flask" generator, it requires this patch:

```
-connexion == 2.2.0
+connexion == 2.6.0
```

I did not test to get working tox tests as well, but should be considered.

I am willing submit a PR here to update the requirements.txt to update the generator so the server launches, tox passes and the container builds successfully.  Let me know if this work is welcomed.

**Comment by ulidtko** [comment]
Also linked: `connexion`-side issue. You can see how many people got it resolved by this exact upgrade.

Please post a PR!

**Comment by jstockdi-marstone** [comment]
On it.  Please assign the ticket to me.

**Comment by jstockdi-marstone** [comment]
@HugoMario @ulidtko 

Good to close this issue?

**Comment by ulidtko** [comment]
@jstockdi-marstone yes, go ahead and close it. Since #782 got merged, there's nothing more to be done here. The fix will become available to users with the next release.

**Comment by jstockdi-marstone** [comment]
Thanks for all the support you do maintaining the code for the community!
