### ISSUE TITLE
Migration from swagger codegen 3.0.21 to 3.0.23 fails due to compilation errors

### ISSUE THREAD

**Issue by SlavchoArsovski** [swagger-api/swagger-codegen-generators#795]
Hi Swagger Codegen team,

I tried to migrate from 3.0.21 to 3.0.23 because of included feature of OAS3 annotations in Spring Java.
During the migration i found 2 issues:

1. Generating SwaggerDocumentationConfig.java fails to compile because in SwaggerDocumentationConfig.mustache there is 2 imports with same class name from two different packages:
import io.swagger.v3.oas.models.info.Contact;
import springfox.documentation.service.Contact;

2. Having default value on query parameter generates following code:
schema:
name: 'offset'
in: "query"
description: 'Position of first item returned'
required: false
schema:
type: integer
format: int32
example: 100
default: 0

@parameter(in = ParameterIn.QUERY, description = "Position of first item returned" ,schema=@Schema(, defaultValue="0")) @Valid @RequestParam(value = "offset", required = false, defaultValue="0") Integer offset
---> schema=@Schema(, defaultValue="0")) has obsolete comma "," which makes the file with compile error

Best,
Slavcho

**Comment by reta** [comment]
@HugoMario that's on me, fix has been submitted (https://github.com/swagger-api/swagger-codegen-generators/pull/796)
